# -*- coding: utf-8 -*-
"""synthetic_visuals_network_violin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117flN62H1v_VeZSw-fgQLSVs5OGZGZAU
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import pandas as pd

cell_types = [
    'Tumor', 'CD8_T', 'CD4_T', 'Treg',
    'B_cell', 'M1_Mac', 'M2_Mac', 'CAF', 'Endothelial'
]

adj = np.array([
    [0.10, 0.30, 0.25, 0.40, 0.20, 0.25, 0.85, 0.70, 0.55],  # Tumor row
    [0.80, 0.15, 0.50, 0.60, 0.30, 0.20, 0.35, 0.40, 0.25],
    [0.40, 0.55, 0.15, 0.65, 0.45, 0.30, 0.40, 0.50, 0.30],
    [0.35, 0.75, 0.70, 0.10, 0.40, 0.55, 0.60, 0.45, 0.20],
    [0.25, 0.40, 0.50, 0.45, 0.10, 0.35, 0.50, 0.55, 0.40],
    [0.25, 0.30, 0.35, 0.60, 0.40, 0.15, 0.60, 0.65, 0.50],
    [0.85, 0.35, 0.40, 0.65, 0.50, 0.60, 0.15, 0.70, 0.45],
    [0.70, 0.40, 0.50, 0.45, 0.55, 0.65, 0.70, 0.10, 0.75],
    [0.55, 0.25, 0.30, 0.20, 0.40, 0.50, 0.45, 0.75, 0.10]
])

# Heatmap
plt.figure(figsize=(9, 7))
sns.heatmap(
    adj,
    annot=True,
    fmt=".2f",
    xticklabels=cell_types,
    yticklabels=cell_types,
    cbar_kws={'label': 'Interaction Strength'}
)
plt.title("Synthetic CTIN")
plt.xlabel("Target Cell Type")
plt.ylabel("Source Cell Type")
plt.tight_layout()
plt.show()

# Simple Rare Cell KL Score Violin Plot

np.random.seed(42)

common_kl = np.random.normal(loc=1.2, scale=0.6, size=120)
rare_kl   = np.random.normal(loc=4.1, scale=1.2, size=80)

df = pd.DataFrame({
    'KL Score': np.concatenate([common_kl, rare_kl]),
    'Group': ['Common cells']*120 + ['Rare cells']*80
})

# Violin plot
plt.figure(figsize=(6, 5))
sns.violinplot(
    x='Group',
    y='KL Score',
    data=df,
    palette='viridis',
    inner='quartile'
)
plt.title("Synthetic KL Scores\n(Rare cells show higher divergence)")
plt.ylabel("KL Divergence Score")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()